const crypto=require("crypto");const PROJECT_ID="pcls-portal",SESSION_COOKIE="pcls_discord_session",MAX_AGE=604800;
function cookieValue(req,name){const raw=String(req.headers.cookie||"");for(const part of raw.split(";")){const[k,...v]=part.trim().split("=");if(k===name)return decodeURIComponent(v.join("="))}return""}
function session(req){const raw=cookieValue(req,SESSION_COOKIE),secret=String(process.env.DISCORD_CLIENT_SECRET||"").trim();if(!raw||!secret)return null;const[a,b]=raw.split(".");if(!a||!b)return null;const e=crypto.createHmac("sha256",secret).update(a).digest("base64url");if(b!==e)return null;try{const p=JSON.parse(Buffer.from(a,"base64url").toString("utf8")),n=Math.floor(Date.now()/1000);return p?.discordId&&p?.exp>n&&p.exp<=n+MAX_AGE+60?p:null}catch{return null}}
function fv(v){return{stringValue:String(v??"")}}
function decode(fields={}){const o={};for(const[k,v]of Object.entries(fields)){if(v.stringValue!==undefined)o[k]=v.stringValue;else if(v.integerValue!==undefined)o[k]=Number(v.integerValue)}return o}
function b64(v){return Buffer.from(v).toString("base64url")}
function jwt(h,p,key){const i=`${b64(JSON.stringify(h))}.${b64(JSON.stringify(p))}`,s=crypto.createSign("RSA-SHA256").update(i).end().sign(key);return`${i}.${s.toString("base64url")}`}
async function token(){const sa=JSON.parse(String(process.env.FIREBASE_SERVICE_ACCOUNT_JSON||"")),n=Math.floor(Date.now()/1000);const assertion=jwt({alg:"RS256",typ:"JWT"},{iss:sa.client_email,sub:sa.client_email,aud:"https://oauth2.googleapis.com/token",iat:n,exp:n+3600,scope:"https://www.googleapis.com/auth/datastore"},sa.private_key.replace(/\\n/g,"\n"));const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion}).toString()}),d=await r.json();if(!r.ok)throw new Error("Google token indisponibil");return d.access_token}
async function find(t,s){for(const[field,value]of [["discordId",s.discordId],["discord_id",s.discordId],["discord",s.discordId],["email",s.email]]){if(!value)continue;const r=await fetch(`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents:runQuery`,{method:"POST",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({structuredQuery:{from:[{collectionId:"utilizatori"}],where:{fieldFilter:{field:{fieldPath:field},op:"EQUAL",value:fv(value)}},limit:1}})});const rows=await r.json().catch(()=>[]);const hit=Array.isArray(rows)?rows.find(x=>x.document):null;if(hit?.document)return{id:String(hit.document.name).split("/").pop(),...decode(hit.document.fields||{})}}return null}
async function update(t,id,data){const url=new URL(`https://firestore.googleapis.com/v1/projects/${PROJECT_ID}/databases/(default)/documents/utilizatori/${encodeURIComponent(id)}`);for(const k of Object.keys(data))url.searchParams.append("updateMask.fieldPaths",k);const r=await fetch(url,{method:"PATCH",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({fields:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,{stringValue:String(v)}]))})});if(!r.ok)throw new Error("Nu s-a putut salva profilul")}
module.exports=async(req,res)=>{res.setHeader("Cache-Control","no-store");if(req.method!=="POST")return res.status(405).json({ok:false});const s=session(req);if(!s)return res.status(401).json({ok:false,error:"Sesiune Discord lipsă"});const name=String(req.body?.name||"").trim();if(!name)return res.status(400).json({ok:false,error:"Nume invalid"});try{const t=await token(),p=await find(t,s);if(!p)return res.status(404).json({ok:false,error:"Profilul Discord nu există în Firestore"});await update(t,p.id,{nume:name,name,displayName:name,numeDiscord:String(s.username||name)});return res.status(200).json({ok:true,name})}catch(e){console.error("update-profile",e);return res.status(500).json({ok:false,error:e.message||"Eroare server"})}};